'use client'
import { Inter } from 'next/font/google'
import './globals.css'
import { UserLocation } from '@/context/UserLocationContext'
import { useState, useEffect } from 'react'
const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const [coord, setCoord] = useState(null)

  useEffect(() => {
    getMyLocation()
  }, [])

  const getMyLocation = () => {
    navigator.geolocation.getCurrentPosition(function (pos) {
      console.log(pos)
      setCoord([pos.coords.latitude, pos.coords.longitude]);
    })
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserLocation.Provider value={{ coord }} >
          {children}
        </UserLocation.Provider>
      </body>
    </html>
  )
}
